# Generated by Django 4.0 on 2021-12-30 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='uniades',
            new_name='unidad',
        ),
    ]
