# Generated by Django 4.0.1 on 2022-01-05 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_rename_uniades_producto_unidad'),
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ordenado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='vendedor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.producto')),
            ],
        ),
        migrations.AlterField(
            model_name='venta',
            name='producto',
            field=models.ManyToManyField(to='Ventas.Orden'),
        ),
    ]
