# Generated by Django 4.0 on 2021-12-29 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TESTmodel',
        ),
    ]
